---
- hosts: localhost
  tasks:
    - name: Running mvn clean
      shell: "mvn clean install"
      register: mvn_result

    - name: Print out maven clean result
      debug: 
        var: mvn_result

    - name: Docker build
      community.docker.docker_image:
        source: build
        build:
          nocache: yes
          path: .
        name: "{{image_name_tag_name}}"
      register: build_result

    - name: Print out docker build result
      debug:
        var: build_result
      
