version: '3.7'
services:
  scheduler:
    image: scheduler:${SCHEDULER_TAG_VERSION}
    container_name: scheduler
    restart: always
    expose:
      - "20000"
      - "40000"
    ports:
      - "20000:20000"
      - "40000:40000"
    networks:
      - dreamer
    volumes:
      - checkin-vol:/home/java-app/config
    environment:
      - JAVA_OPTS= -XX:+UseZGC -Xss1024k -Xms64M -Xmx128M -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:40000
      - TZ=Asia/Taipei

networks:
  dreamer:
    external: true
    
volumes:
  checkin-vol:
